using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using nhom1_sales_and_inventory_management.Infrastructure.Data;

#nullable disable

namespace nhom1_sales_and_inventory_management.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260619143000_AddProductVariantsAndColors")]
public partial class AddProductVariantsAndColors : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE "ProductVariants" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE CASCADE,
                "Name" character varying(80) NOT NULL,
                "Sku" character varying(120) NOT NULL,
                "OriginalPrice" numeric(18,2) NOT NULL,
                "SalePrice" numeric(18,2) NULL,
                "Quantity" integer NOT NULL,
                "ReserveStock" integer NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE
            );
            CREATE UNIQUE INDEX "IX_ProductVariants_Sku" ON "ProductVariants" ("Sku");
            CREATE INDEX "IX_ProductVariants_ProductId" ON "ProductVariants" ("ProductId");
            CREATE TABLE "ProductVariantColors" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ProductVariantId" integer NOT NULL REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE,
                "Name" character varying(80) NOT NULL,
                "HexCode" text NULL,
                "Quantity" integer NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE
            );
            CREATE UNIQUE INDEX "IX_ProductVariantColors_ProductVariantId_Name"
                ON "ProductVariantColors" ("ProductVariantId", "Name");
            INSERT INTO "ProductVariants"
                ("ProductId", "Name", "Sku", "OriginalPrice", "SalePrice", "Quantity", "ReserveStock", "IsActive")
            SELECT p."Id", 'Mặc định', 'SP-' || p."Id" || '-DEFAULT',
                CASE WHEN p."OriginalPrice" > 0 THEN p."OriginalPrice" ELSE p."SellingPrice" END,
                CASE WHEN p."SalePrice" > 0 AND p."SalePrice" < p."OriginalPrice" THEN p."SalePrice" ELSE NULL END,
                COALESCE(i."Quantity", 0), COALESCE(i."ReserveStock", 0), TRUE
            FROM "Products" p LEFT JOIN "Inventories" i ON i."ProductId" = p."Id";
            INSERT INTO "ProductVariantColors" ("ProductVariantId", "Name", "Quantity", "IsActive")
            SELECT v."Id", 'Mặc định', v."Quantity", TRUE FROM "ProductVariants" v;
            ALTER TABLE "ProductImages" ADD COLUMN "ProductVariantColorId" integer NULL;
            UPDATE "ProductImages" image SET "ProductVariantColorId" = color."Id"
            FROM "ProductVariants" variant
            JOIN "ProductVariantColors" color ON color."ProductVariantId" = variant."Id"
            WHERE variant."ProductId" = image."ProductId";
            ALTER TABLE "ProductImages" DROP CONSTRAINT "FK_ProductImages_Products_ProductId";
            DROP INDEX IF EXISTS "IX_ProductImages_ProductId_SortOrder";
            ALTER TABLE "ProductImages" ALTER COLUMN "ProductVariantColorId" SET NOT NULL;
            ALTER TABLE "ProductImages" DROP COLUMN "Version";
            ALTER TABLE "ProductImages" DROP COLUMN "ProductId";
            ALTER TABLE "ProductImages" ADD CONSTRAINT "FK_ProductImages_ProductVariantColors_ProductVariantColorId"
                FOREIGN KEY ("ProductVariantColorId") REFERENCES "ProductVariantColors" ("Id") ON DELETE CASCADE;
            CREATE INDEX "IX_ProductImages_ProductVariantColorId_SortOrder"
                ON "ProductImages" ("ProductVariantColorId", "SortOrder");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE "ProductImages" ADD COLUMN "ProductId" integer NULL;
            ALTER TABLE "ProductImages" ADD COLUMN "Version" character varying(80) NULL;
            UPDATE "ProductImages" image SET "ProductId" = variant."ProductId", "Version" = variant."Name"
            FROM "ProductVariantColors" color
            JOIN "ProductVariants" variant ON variant."Id" = color."ProductVariantId"
            WHERE color."Id" = image."ProductVariantColorId";
            ALTER TABLE "ProductImages" DROP CONSTRAINT "FK_ProductImages_ProductVariantColors_ProductVariantColorId";
            DROP INDEX IF EXISTS "IX_ProductImages_ProductVariantColorId_SortOrder";
            ALTER TABLE "ProductImages" DROP COLUMN "ProductVariantColorId";
            ALTER TABLE "ProductImages" ALTER COLUMN "ProductId" SET NOT NULL;
            ALTER TABLE "ProductImages" ADD CONSTRAINT "FK_ProductImages_Products_ProductId"
                FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;
            CREATE INDEX "IX_ProductImages_ProductId_SortOrder" ON "ProductImages" ("ProductId", "SortOrder");
            DROP TABLE "ProductVariantColors";
            DROP TABLE "ProductVariants";
            """);
    }
}
